/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_srtaction_free: (a: number, b: number) => void;
export const __wbg_srtreceiver_free: (a: number, b: number) => void;
export const __wbg_srtstats_free: (a: number, b: number) => void;
export const srtaction_data: (a: number) => [number, number];
export const srtaction_kind: (a: number) => number;
export const srtaction_takeData: (a: number) => [number, number];
export const srtaction_text: (a: number) => [number, number];
export const srtaction_wait_ms: (a: number) => number;
export const srtreceiver_getStats: (a: number) => number;
export const srtreceiver_handle_datagram: (a: number, b: number, c: number, d: number) => [number, number];
export const srtreceiver_isClosed: (a: number) => number;
export const srtreceiver_isHandshakeComplete: (a: number) => number;
export const srtreceiver_new: () => number;
export const srtreceiver_newWithLatency: (a: number) => number;
export const srtreceiver_newWithSeed: (a: number) => number;
export const srtreceiver_poll: (a: number, b: number) => [number, number];
export const srtreceiver_sendMessage: (a: number, b: number, c: number, d: number) => [number, number];
export const srtstats_bandwidthBps: (a: number) => number;
export const srtstats_rttMs: (a: number) => number;
export const srtstats_rxAck: (a: number) => number;
export const srtstats_rxBelated: (a: number) => number;
export const srtstats_rxBuffered: (a: number) => number;
export const srtstats_rxBytes: (a: number) => number;
export const srtstats_rxData: (a: number) => number;
export const srtstats_rxDropped: (a: number) => number;
export const srtstats_rxLoss: (a: number) => number;
export const srtstats_rxNak: (a: number) => number;
export const srtstats_rxRetransmit: (a: number) => number;
export const srtstats_txBuffered: (a: number) => number;
export const srtstats_txBytes: (a: number) => number;
export const srtstats_txData: (a: number) => number;
export const srtstats_txLoss: (a: number) => number;
export const srtstats_txRetransmit: (a: number) => number;
export const srtstats_elapsedMs: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
